USE ROLE ACCOUNTADMIN;

-- Create database and schemas to separate processing, execution, and deployment
CREATE OR REPLACE DATABASE ML_SNOWPARK_CI_CD_DB;
USE DATABASE ML_SNOWPARK_CI_CD_DB;
CREATE OR REPLACE SCHEMA DATA_PROCESSING;
CREATE OR REPLACE SCHEMA ML_PROCESSING;

-- Create a test UDF
CREATE OR REPLACE FUNCTION DATA_PROCESSING.MULTIPLY(X NUMBER(35,4), Y NUMBER(35, 4))
RETURNS NUMBER(35,4)
    AS 
$$
   X * Y
$$;

SELECT DATA_PROCESSING.MULTIPLY(499, 599) AS PRODUCT;